---

- name: 'Install git'
  apt:
    force: yes
    name: 'git'
    state: 'present'

- name: 'Git clone'
  git:
    repo: 'https://github.com/arsenbig/web-application-epam.git'
    dest: /opt/web-application-epam
